name: build

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: 'Setup Flutter'
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.38.9'
        channel: 'stable'

    - name: 'Get Packages'
      run: flutter pub get
